services:
  bazarr:
    image: ghcr.io/hotio/bazarr
    container_name: bazarr
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "6767:6767"
    
    volumes:
      - ~/volumes/bazarr/config:/config
      - ~/volumes/bazarr/data:/data
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORTS=6767/tcp,6767/udp

  bookshelf:
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    container_name: bookshelf
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - 8787:8787

    volumes:
      - ~/volumes/bookshelf/config:/config
      - ~/volumes/bookshelf/data:/data

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam

  lidarr:
    image: ghcr.io/hotio/lidarr
    container_name: lidarr
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "8686:8686"
    
    volumes:
      - ~/volumes/lidarr/config:/config
      - ~/volumes/lidarr/data:/data
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam

  overseerr:
    image: ghcr.io/hotio/overseerr
    container_name: overseerr
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "5055:5055"
    
    volumes:
      - ~/volumes/overseerr/config:/config
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    restart: always

    networks:
      - arr-stack
    ports:
      - "9696:9696"
        
    volumes:
      - ~/volumes/prowlarr/config:/config
        
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam

  plex:
    image: ghcr.io/hotio/plex
    container_name: plex
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "32400:32400"

    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
      # - PLEX_CLAIM_TOKEN
      # - PLEX_ADVERTISE_URL=plex.lykoi-mark.ts.net
      # - PLEX_NO_AUTH_NETWORKS=
      - PLEX_BETA_INSTALL=false
      - PLEX_PURGE_CODECS=false
    
    volumes:
      - ~/volumes/plex/config:/config
      - ~/volumes/plex/transcode:/transcode
      - ~/volumes/plex/data:/data

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "8080:8080"
    
    volumes:
      - ~/volumes/qbittorrent/config:/config
      - ~/volumes/qbittorrent/data:/data
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORTS=8080/tcp,8080/udp
      - LIBTORRENT=v1
  
  qui:
    image: ghcr.io/hotio/qui
    container_name: qui
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "7476:7476"
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    
    volumes:
      - ~/volumes/qui/config:/config

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "7878:7878"
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    
    volumes:
      - ~/volumes/radarr/config:/config
      - ~/volumes/radarr/data:/data

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "8989:8989"
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    
    volumes:
      - ~/volumes/sonarr/config:/config
      - ~/volumes/sonarr/data:/data
        
networks:
  arr-stack:
    name: arr-stack
    driver: bridge
