services:
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    restart: always
    
    network_mode: bridge
    ports:
      - "6767:6767"
    
    volumes:
      - zb-tyEON:/config
      - zb-3PwGI:/data
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORTS=6767/tcp,6767/udp

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: always
    
    network_mode: bridge
    ports:
      - "8686:8686"
    
    volumes:
      - zb-yu_2y:/config
      - zb-3PwGI:/data
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam

  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    restart: always
    
    network_mode: bridge
    ports:
      - "5055:5055"
    
    volumes:
      - zb-kQWx1:/config
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: always
    
    network_mode: bridge
    ports:
      - "9696:9696"
        
    volumes:
      - zb-u3UTp:/config
        
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam

  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    restart: always
    
    network_mode: bridge
    ports:
      - "32400:32400"

    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
      # - PLEX_CLAIM_TOKEN
      - PLEX_ADVERTISE_URL=plex.lykoi-mark.ts.net
      # - PLEX_NO_AUTH_NETWORKS=
      - PLEX_BETA_INSTALL=false
      - PLEX_PURGE_CODECS=false
    
    volumes:
      - zb-P1o4k:/config
      - zb-cxnfU:/transcode
      - zb-3PwGI:/data

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    restart: always
    
    network_mode: bridge
    ports:
      - "8080:8080"
    
    volumes:
      - zb-Gv2lz:/config
      - zb-3PwGI:/data
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORTS=8080/tcp,8080/udp
      - LIBTORRENT=v1
  
  qui:
    container_name: qui
    image: ghcr.io/hotio/qui
    restart: always
    
    network_mode: bridge
    ports:
      - "7476:7476"
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    
    volumes:
      - zb-fv7AD:/config

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: always
    
    network_mode: bridge
    ports:
      - "7878:7878"
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    
    volumes:
      - zb-8Va75:/config
      - zb-3PwGI:/data

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    restart: always
    
    network_mode: bridge
    ports:
      - "8989:8989"
    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    
    volumes:
      - zb-qPSBH:/config
      - zb-3PwGI:/data

volumes:
  zb-tyEON:
      external: true
  zb-yu_2y:
      external: true
  zb-kQWx1:
      external: true
  zb-u3UTp:
      external: true
  zb-Gv2lz:
      external: true
  zb-fv7AD:
      external: true
  zb-8Va75:
      external: true
  zb-qPSBH:
      external: true
  zb-3PwGI:
      external: true
  zb-P1o4k:
  zb-cxnfU:





