services:
    mssql:
        container_name: mssql
        image: mcr.microsoft.com/mssql/server:2025-latest
        restart: always

        network_mode: bridge
        ports:
            - 1433:1433

        volumes:
            - zb-_CEuG:/var/opt/mssql

        env_file: .env

volumes:
  zb-_CEuG:
    external: true
