services:
    plex:
        container_name: plex
        image: plexinc/pms-docker:latest
        restart: always
        network_mode: host
        volumes:
            - plex_transcode:/transcode
            - zb-P1o4k:/config
            - zb-6Q5xn:/data
        environment:
            TZ: "Europe/Amsterdam"
            
volumes:
    plex_transcode:
        name: plex_transcode
    zb-P1o4k:
        external: true
    zb-6Q5xn:
        external: true
