services:
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        restart: always
        network_mode: host
        env_file: .env
        
        devices:
            - dev/dri:/dev/dri

        volumes:
            - zb-P1o4k:/config
            - zb-6Q5xn:/medias 
            
volumes:
    zb-P1o4k:
        external: true
    zb-6Q5xn:
        external: true
