services:
  ocular:
    image: ghcr.io/simonwep/ocular:v2.0
    container_name: ocular
    restart: unless-stopped
    
    volumes:
      - ~/volumes/ocular/data:/data/genesis
    
    ports:
      - 3030:80

    environment:
      - GENESIS_JWT_SECRET
      - GENESIS_CREATE_USERS
      - GENESIS_JWT_TOKEN_EXPIRATION
