services:
    trips:
        image: ghcr.io/itskovacs/trip:1
        container_name: trips
        restart: unless-stopped

        ports:
            - 8060:8000

        volumes:
          - ~/volumes/trips:/app/storage

        environment:
            TZ: "Europe/Amsterdam"

