services:
    trips:
        container_name: trips
        image: ghcr.io/itskovacs/trip:1
        restart: always
        network_mode: bridge
        ports:
            - 8060:8000
        volumes:
            - zb-zDT8X:/app/storage
        environment:
            TZ: "Europe/Amsterdam"
volumes:
    zb-zDT8X:
        external: true
