services:
    vaultwarden:
        container_name: vaultwarden
        image: vaultwarden/server:latest
        restart: always
        network_mode: bridge
        ports:
            - 8090:80
        volumes:
            - zb-kocSY:/data
        env_file:
            - .env
            
volumes:
    zb-kocSY:
        external: true
