# Arcane Docker Compose Configuration
# Generated at 11/12/2025, 14:14:58

services:
  arcane:
      image: ghcr.io/getarcaneapp/arcane:latest
      container_name: arcane
      restart: always
      
      ports:
        - 80:3552
      
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - zb-Ob2pB:/app/data
      
      environment:
        - APP_URL=http://homelab003.lykoi-mark.ts.net
        - PUID=1000
        - PGID=1000
        - ENCRYPTION_KEY=3941efab29824813abc32575fe3b72556cf92269e900beb9555185787d80aca9
        - JWT_SECRET=efac72bad4ea7f811dab04439be2613770517fe5a2eca0d22717e62d0ab346fe
        - LOG_LEVEL=info
        - LOG_JSON=false
        - OIDC_ENABLED=false
        - DATABASE_URL=file:data/arcane.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate
        
volumes:
  zb-Ob2pB:
    external: true