services:
    zerobyte:
        container_name: zerobyte
        image: ghcr.io/nicotsx/zerobyte:v0.15
        restart: always
        network_mode: bridge
        ports:
            - 4096:4096
        volumes:
            - /var/lib/zerobyte:/var/lib/zerobyte:rshared
            - /etc/localtime:/etc/localtime:ro
            - /run/docker/plugins:/run/docker/plugins
            - /var/run/docker.sock:/var/run/docker.sock
            - /AppData:/AppData
        environment:
            TZ: "Europe/Amsterdam"
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse:/dev/fuse
