services:
    zerobyte:
      image: ghcr.io/nicotsx/zerobyte:latest
      container_name: zerobyte
      restart: unless-stopped
        
      ports:
          - 4096:4096
        
      volumes:
          - /var/lib/zerobyte:/var/lib/zerobyte:rshared
          - /etc/localtime:/etc/localtime:ro
          - /home/tha/.config/rclone:/root/.config/rclone:ro
          - ~/volumes:/volumes
        
      environment:
          PUID: 1000
          PGID: 1000
          TZ: "Europe/Amsterdam"
        
      cap_add:
          - SYS_ADMIN

      devices:
          - /dev/fuse:/dev/fuse
        

      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 512M

{{ if eq .chezmoi.hostname "homelab-002" }}
      labels:
        - "diun.enable=true"
{{ end }}
