services:
    zerobyte:
      image: ghcr.io/nicotsx/zerobyte:v0.15
      container_name: zerobyte
      restart: unless-stopped
        
      ports:
          - 4096:4096
        
      volumes:
          - /var/lib/zerobyte:/var/lib/zerobyte:rshared
          - /etc/localtime:/etc/localtime:ro
          - /run/docker/plugins:/run/docker/plugins
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/tha/.config/rclone:/root/.config/rclone:ro
          - ~/volumes:/volumes
        
      environment:
          TZ: "Europe/Amsterdam"
        
      cap_add:
          - SYS_ADMIN

      devices:
          - /dev/fuse:/dev/fuse
        
      deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 1024M
